

const BASE_API_URL = process.env.REACT_APP_BASE_API_URL;
const FAQ_ENDPOINT = `${BASE_API_URL}faq`;
const CONTACT_ENDPOINT = `${BASE_API_URL}contact`;
const PROJECT_ENDPOINT = `${BASE_API_URL}project`;
const SETTING_ENDPOINT = `${BASE_API_URL}setting`;
export {
    FAQ_ENDPOINT, CONTACT_ENDPOINT, PROJECT_ENDPOINT, SETTING_ENDPOINT
}