// Generated by https://quicktype.io

export type ProjectResponse = {
    status:  string;
    data:    Project[];
    message: string;
}

export type ProjectOneResponse = {
    status:  string;
    data:    Project;
    message: string;
}

export enum TypeProject  {
 PROJECT = "project",
 SERVICE = "service"
}

export type Project = {
    id:           number;
    thumbnailSrc: string;
    main_image:   string;
    title:        string;
    description:  string;
    subtitle:     string;
    totalPrice:   string;
    monthlyPrice: string;
    area:         string;
    type:         TypeProject;
    flag:         string;
    createdAt:    string;
    updatedAt:    string;
    Images:       Image[];
}

export type Image = {
    id:        number;
    image_url: string;
    createdAt: string;
    updatedAt: string;
    ProjectId: number;
}
