// Generated by https://quicktype.io

export type SettingResponse = {
    status:  string;
    data:    Setting;
    message: string;
}

export type Setting = {
    id:             number;
    company_name:   string;
    logo_url:       string;
    company_email:  string;
    address:        string;
    codigo_postal:  string;
    facebook_url:   string;
    instagram_url:  string;
    twitter_url:    string;
    description:    string;
    us_title:       string;
    us_description: string;
    us_image:       string;
    main_title:     string;
    main_subtitle:  string;
    wp_message:     string;
}
